apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - name: "80"
      port: 80
      targetPort: 80